version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: meu_postgres
    environment:
      POSTGRES_USER: hari
      POSTGRES_PASSWORD: hari
      POSTGRES_DB: hari
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: